import './globals.css'
import Providers from '../components/providers';
import SignInButton from "../components/SignInButton";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ Component, pageProps, Session ,children }) {
  return (
    <html lang="en">
      <body className='text-white bg-black'>
      <Providers>
        <SignInButton/>
        {children}
      </Providers>
      </body>
    </html>
  );
}
