import './globals.css'
import Providers from './components/providers';
import SignInTemp from "./components/signInn";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ Component, pageProps, Session ,children }) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <SignInTemp/>
        {children}
      </Providers>
      </body>
    </html>
  );
}
